name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
